### ISSUE TITLE
Icon mode

### ISSUE THREAD

**Issue by KaspianDev** [maciekmm/container-tabs-sidebar#103]
Hello, I would like to suggest adding a mode that hides the tab title, and only shows icons to save space

**Comment by maciekmm** [comment]
Hello,

you can achieve this by using the following CSS in Container Tabs Sidebar preferences (about:addons -> CTS -> Preferences)

```css
.container-tab-title, .container-tab-close, .container-tab-count, .container-title {
  display: none !important;
}
```

Though, Firefox won't let you make the sidebar narrower than a ~`200px`, to achieve a narrower sidebar, you will have to edit `userChrome.css` (https://github.com/maciekmm/container-tabs-sidebar#appearance-modifications)
by specifying `min-width: 0` for the `#sidebar-box` id.
