### ISSUE TITLE
Move the mute icon element between the favicon and the title

### ISSUE THREAD

**Issue by tkapias** [maciekmm/container-tabs-sidebar#105]
Hi,

Thanks for this add-on, coupled with "Temporary containers" it's perfect.
I customized the CSS a bit (which I'll put at the bottom).
***
But there is still one thing that bothers me, the position of the mute icons.
When you move the mouse on a tab to mute, the close icon appears and the mute icon moves to the left, it's frustrating.

Could you modify the basic design so that the mute would be between the favicon and the title?
So the hover won't move anything.
***
For all intents and purposes, here is my custom CSS (for a dark/grey system theme): 
```scss
:root {
  --font-size: 12px;
  --color-background: #333;
  --color-container-background: #2B2D30;
  --color-tab-background: #333;
  --color-hover: #2E2E2E;
  --color-focus: #424242;
}
.container-header {
    font-size: 10px;
    border-left-width: 0.4em;
}
.container-header .container-icon {
    display: none;
}
.container-header .container-title {
    text-transform: uppercase;
    margin-left: 0.8em;
    color: #999;
    padding: 8px 0px;
}
.container-header:last-of-type {
    border-color: green;
}
li.container:last-of-type .container-title {
    visibility: hidden;
    position: relative;
}
li.container:last-of-type .container-title:after {
    visibility: visible;
    position: absolute;
    left: 0;
    content: "tmp";
}
.container-tab-count {
    padding-left: 0;
    margin-left: auto;
    color: #ccc;
}
.container-tab-count::before, .container-tab-count::after {
    content: '';
}
.container-actions {
    margin-left: 0.3em;
    margin-right: 0.3em;
}
.container-actions .container-action {
    margin: 0;
    padding: 5px;
    font-size: 14px;
}
.container-tabs {
    width: 100%;
    display: block;
    padding-inline-start: 0;
}
.container-tab-title {
    text-transform: lowercase;
    margin-left: 0.8em;
    flex-basis: 100%;
    color: #999;
    padding: 5px 0px;
}
.tab-active .container-tab-title {
    color: #fff;
    text-transform: none;
}
.container-tab-action--mute {
    height: 12px;
    margin: auto;
}
.container-tab-close {
    padding: 0em 0.2em;
    margin-left: 0.3em;
    font-size: 14px;
}

```

Vanilla :
![image](https://user-images.githubusercontent.com/45816387/160351493-8a3bf27a-4194-4f23-93a4-e445e4be1f8e.png)

Custom :
![image](https://user-images.githubusercontent.com/45816387/160351561-95b47fc2-c111-4585-88bf-5fee1348d90a.png)

**Comment by maciekmm** [comment]
Hi @tkapias,

that theme looks slick! :) 

You can move the `mute` icon element between favicon and title using the following css:
```css
.container-tabs .favicon {
    order: 0;
}
.container-tab-action--mute {
    order: 1;
}
.container-tab-title {
    order: 2;
}
.container-tab-close {
    order: 3;
}
```

![image](https://user-images.githubusercontent.com/3267517/160402217-e0aeb7d9-cfcd-4e88-b4d5-42fe4fac53dd.png)


You might want to tweak the margins a bit.

Post your final theme, I think some people may be interested to use it. :)
