### ISSUE TITLE
Colorful tabs support?

### ISSUE THREAD

**Issue by moookino** [maciekmm/container-tabs-sidebar#121]
Hi @maciekmm 

Is it possible to implement support for colorful tabs? E.g. to set color per domain or just random to easily navigate through them?
There's was the way to use that with TST with additional extension https://addons.mozilla.org/en-US/firefox/addon/tst-colored-tabs/ 

Thanks for your great work

**Comment by maciekmm** [comment]
Hi @moookino 

I feel like this feature would make add too much bloat to CTS.

If we decide to implement this it'd most likely be via some form of an addon API like it is with TST.

Currently, if you want to have a color per domain, you can hack it a little bit, by using the following CSS in the addon settings

```css
a.container-tab[href*="google.com"] {
   background: green !important;
}
```

![image](https://github.com/maciekmm/container-tabs-sidebar/assets/3267517/3d0b53d5-7366-4ead-aa44-bfe1345c5581)

You can also be a little bit more creative and do something like this:

```css
a.container-tab[href^="https://a"], a.container-tab[href^="https://www.a"] {
   background: blue !important;
}
a.container-tab[href^="https://g"], a.container-tab[href^="https://www.g"] {
   background: green !important;
}
/* .. etc */
```

This will color your tabs based on what letter the domain starts with.


Not sure if that helps :)
