### ISSUE TITLE
Option to reverse tab ordering

### ISSUE THREAD

**Issue by david-k** [maciekmm/container-tabs-sidebar#67]
Hi,
would it be possible to add an option to reverse the order of the tabs? Currently, the oldest tab is at the top, and since I have quite a lot of tabs open, I need to scroll all the way to the bottom to see the most recent ones.
Btw, I really like how fast this extension is compared to Tree Style Tabs, which always takes a couple of seconds to load. (I just have way to many tabs open...)

EDIT: An alternative solution could be to restore the last scrolling position.

**Comment by maciekmm** [comment]
You can add a custom css in the add-on preferences to achieve this:

```css
.container-tabs {
    display: flex;
    flex-direction: column-reverse;
}
```
