### ISSUE TITLE
Close Tab Icon Overlay Over Favicon on macOS

### ISSUE THREAD

**Issue by Nonameentered** [maciekmm/container-tabs-sidebar#69]
Instead of having the close tab button be on the right edge of the tab (where it can overlap with the scrollbar), could there be an option to move the button to appear on top of the favicon?
Otherwise, is it possible to hide the scrollbar.

**Comment by maciekmm** [comment]
Thank you for the question/report. I assume you are using OSX? Because I can't think of any other OSs that make the scrollbars overlap.

You can go to addons preferences and in the css section paste the following code. It should fix your issues ;)
```css
.container-tab-close, .container-tab-close:hover {
   position: absolute;
   background: #333;
   border-radius: 20px;
   padding: 2px;
   left: 2px;
   top: 50%;
   transform: translateY(-50%);
}
```
